### ISSUE TITLE
Adding users with upper case letters make them lower cased

### ISSUE THREAD

**Issue by PavelSusloparov** [mineiros-io/terraform-github-team#33]
I'm trying to add existing users from my GitHub organization to the terraform state.

```
module "admins" {
  source  = "mineiros-io/team/github"
  version = "0.3.0"

  name = "Admins"
  privacy = "closed"

  maintainers = [
    "PavelSusloparov"
  ]
}
```

terraform plan gives me
```
  # module.admins.github_team_membership.team_membership["pavelsusloparov"] will be created
  + resource "github_team_membership" "team_membership" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = "79035"
      + username = "pavelsusloparov"
    }
```

I expect the username to be camelcase, as I specified in the maintainers section.

pavelsusloparov is not my GitHub name, PavelSusloparov is. 

Please advise.

**Comment by mariux** [comment]
Hi @PavelSusloparov.. thanks for taking the time reporting this issue and thanks for giving our modules a try ;)

This should not make a difference as GitHub user names are case-insensitive. The only question is if it will create an idempotent state. but no matter what for the sake of not having a confusing plan, we should fix it. 

I will add a test case for this to validate state will settle no matter what the case is.

**Comment by mariux** [comment]
Added a test to validate my assumption. the case does not matter. So this is just a cosmetic issue in the plan and an apply will work as expected adding the user to the team no matter the case. 

I still added a fix but this will still not reflect the actual GitHub user name but will preserve the case in the plan that is used in the configuration. Will be released with a later release.

See also: #34 and test output.

**Comment by soerenmartius** [comment]
Hey @PavelSusloparov , please let us know if there are any other concerns or if we may close this issue. Thank You!

**Comment by mariux** [comment]
closed due to merging the fix to default branch.... pls reopen if you feel it was not fixed.. will be included in the next release.

**Comment by PavelSusloparov** [comment]
Thank you for clarifying it! No actions needed at this point.
