### ISSUE TITLE
maintain_repositories & triage_repositories support

### ISSUE THREAD

**Issue by PavelSusloparov** [mineiros-io/terraform-github-team#37]
This is a feature request.

I'm terraforming relationship between a team and its repositories.

When I source repositories from GitHub API I have the following response
```
[
  {
    "name": "name",
    "permissions": {
        "pull": false,
        "triage": false,
        "push": false,
        "maintain": true,
        "admin": false
      }
      ...
  },
  ...
]
```

Next, I'm transforming this to 

```
  admin_repositories = [...]
  push_repositories = [...]
  pull_repositories = [...]
```

I would like to have maintain_repositories & triage_repositories lists.
```
  admin_repositories = [...]
  maintain_repositories = [...]
  push_repositories = [...]
  triage_repositories = [...]
  pull_repositories = [...]
```

As a workaround, I assign maintain_repositories to admin_repositories and triage_repositories to push_repositories.
However, it gives the team more permissions, than necessary. 

Full list of permissions: https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization

**Comment by PavelSusloparov** [comment]
https://github.com/mineiros-io/terraform-github-team/pull/38

**Comment by soerenmartius** [comment]
Hey @PavelSusloparov ,

Sorry only found some time to read this issue now. Thanks for bringing this to our attention and also thanks for providing this PR. By the time we've published this module `maintain_repositories`, `admin_repositories` and `triage_repositories` did not exist in the provider. However, we keep adding features frequently (mostly when we need it for one of our customers or when provided by the community). Also, thanks for providing the PR. I am gonna review it in detail and come back to you asap.

**Comment by soerenmartius** [comment]
cc @mariux

**Comment by PavelSusloparov** [comment]
I can see that p/r has been merged. Perfect, thanks!
Waiting on the new release tag.

**Comment by soerenmartius** [comment]
Hi @PavelSusloparov ,

We just released [v0.5.1](https://github.com/mineiros-io/terraform-github-team/releases/tag/v0.5.1) now. 
Once again, thanks for your contribution! We appreciate that :)

**Comment by PavelSusloparov** [comment]
Yay! Thank you!

**Comment by PavelSusloparov** [comment]
Bug fix. https://github.com/mineiros-io/terraform-github-team/pull/40
