### ISSUE TITLE
Bumping tf provider  required_version to 1.0.0

### ISSUE THREAD

**Issue by SMR39** [mineiros-io/terraform-github-team#44]
https://github.com/mineiros-io/terraform-github-team/blob/master/versions.tf#L6

hello I was wondering if we could bump the required tf version to 1.0.0 

`Terraform v1.0.0 intentionally has no significant changes compared to Terraform v0.15.5. You can consider the v1.0 series as a direct continuation of the v0.15 series`

**Comment by soerenmartius** [comment]
Hi @SMR39, 

I've prepared the upgrade to Terraform `v1` in #43. Once the team reviewed and approved the PR, I am gonna issue a new release.

Thank You!
