### ISSUE TITLE
Add support for `integrations/github` ~5.0

### ISSUE THREAD

**Issue by 0x46616c6b** [mineiros-io/terraform-github-team#62]
GitHub releases a week ago a new major version of the provider: https://github.com/integrations/terraform-provider-github/releases

The module should support that version :-)

**Comment by soerenmartius** [comment]
Hi @0x46616c6b , 

Thanks for reaching out. We added support for the `5.x` provider back in October in https://github.com/mineiros-io/terraform-github-team/releases/tag/v0.9.0.

Thanks and let me know if there's anything else we can help you with!
